CREATE TABLE ceasar(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    user_id INTEGER NOT NULL,
    shift INTEGER NOT NULL,
    data VARCHAR(2048) NOT NULL, -- base64 encoded
    deleted BOOLEAN DEFAULT FALSE NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES users(id)
)
